### ISSUE TITLE
Error Messages not translated

### ISSUE THREAD

**Issue by fuchsbart** [wirecard/prestashop-ee#233] opened 2019-10-30 15:58 UTC
### Prerequisites

- [x] I have my [server set up correctly](https://github.com/wirecard/prestashop-ee/wiki/Installation#requirements).
- [x] I am using a [supported version of PrestaShop](https://github.com/wirecard/prestashop-ee/wiki#download-prestashop-shop-module).

### Versions

**PrestaShop version:**
1.7.5.1
**PHP version:** ...  
7.1

### Issue

The error messages are displayed in English, although the whole shop is in German.
A translation of the module in the Prestashop backend is not possible, no strings are displayed here.

**Comment by tomazpu** [comment] 2019-10-31 08:31
Hello, 

@fuchsbart can u please provide us with more detail, it's very hard to say what is not translated.

As we are using are API, it can be that the error massage is comming from there thats why you cannot find it in the backend.

**Comment by tomazpu** [comment] 2019-11-04 08:56
Hello @fuchsbart,

I reproduced the issue that the error messages coming from the engine are not in the same language as the shop. We will fix the issue as soon as possible.

Best regards,
Tomaz

**Comment by tomazpu** [comment] 2019-11-15 12:58
Hi @fuchsbart, 

we fixed the issue of the correct language code being sent to the engine.  Unfortunately, this is only one part of the problem we still need to wait for the fix on the engine site.

Thank you.
Best regards, Tomaz

**Comment by fuchsbart** [comment] 2020-02-05 13:06
Hello @tomazpu, is there any update about fixing the translation of the error messages?

Thanks

**Comment by fuchsbart** [comment] 2020-02-20 10:37
Hi @tomazpu, should this issue be solved with release 2.7.0?

**Comment by cpfoser** [comment] 2020-02-21 09:05
Hi @fuchsbart, 

we are on the same page that not translated error messages do not have a good user experience for the customer. Therefore, we really tried to rise the importance withinour gateway team to find a solution to provide localized error messages. 

As we are also the consumer of the gateway we need to wait until a solution is provided and connot speed it up ourselves. Thus, I will close this issue because i cannot be solved by our shop-extension team. 

For further information I kindly advise you to reach out directly to the wirecard support. (support@wirecard.com)

Best regards,
Caroline
Wirecard Shop Systems Team

**Closed by cpfoser** 2020-02-21 09:05 UTC
Labels: enhancement, issue
